
  - name: Creating directory for Prometheus
    file:
      path: ~/prometheus
      state: directory
 
  - name: Installing and extracting Prometheus
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
      dest: ~/prometheus
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: Copying Prometheus to /usr/local/bin
    shell: |
      cd ~/prometheus/prometheus*
      cp -r . /usr/local/bin/prometheus

  - name: Moving the Prometheus systemd Service unit file
    copy:
      src: prom.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 777

  - name: Starting/Restarting prometheus
    tags: resprom
    service:
      name: prom
      state: restarted
      enabled: true
